# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import ordermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(null=True, upload_to=ordermanager.models.unique_file_path),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_type',
            field=models.CharField(choices=[('1', 'Computer equipment'), ('2', 'Audio'), ('3', 'Video'), ('4', 'Cabling')], default='1', max_length=1),
        ),
    ]
