# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0002_auto_20180604_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('1', 'Was it easy to request the service?')], default='1', max_length=1)),
                ('answer', models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Dissatisfied'), ('4', 'Very dissatisfied')], default='1', max_length=1)),
                ('questionTwo', models.CharField(choices=[('1', 'What was the quality of the service?')], default='1', max_length=1)),
                ('answerTwo', models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Dissatisfied'), ('4', 'Very dissatisfied')], default='1', max_length=1)),
                ('questionThree', models.CharField(choices=[('1', 'How did the person who made the service treat with you?')], default='1', max_length=1)),
                ('answerThree', models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Dissatisfied'), ('4', 'Very dissatisfied')], default='1', max_length=1)),
                ('questionFour', models.CharField(choices=[('1', 'What is the degree of satisfaction with regard to the time when the order was done?')], default='1', max_length=1)),
                ('answerFour', models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Dissatisfied'), ('4', 'Very dissatisfied')], default='1', max_length=1)),
                ('request_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_set', to='ordermanager.Request')),
            ],
        ),
    ]
