# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0004_auto_20180604_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='answerFive',
            field=models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Unsatisfied'), ('4', 'Very Unsatisfied')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='poll',
            name='questionFive',
            field=models.CharField(choices=[('1', 'What is yout level of satisfaction?')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer',
            field=models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Unsatisfied'), ('4', 'Very Unsatisfied')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answerFour',
            field=models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Unsatisfied'), ('4', 'Very Unsatisfied')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answerThree',
            field=models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Unsatisfied'), ('4', 'Very Unsatisfied')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answerTwo',
            field=models.CharField(choices=[('1', 'Very satisfied'), ('2', 'Satisfied'), ('3', 'Unsatisfied'), ('4', 'Very Unsatisfied')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='questionFour',
            field=models.CharField(choices=[('1', 'How do you feel about the service the technician performed?')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='questionThree',
            field=models.CharField(choices=[('1', 'How do you feel about the behavior of the technician?')], default='1', max_length=1),
        ),
    ]
