# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0006_activity_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='observations',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='technical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_technical_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
