# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0007_auto_20180605_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
