# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0010_auto_20180606_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('1', 'Maintenance of computer equipment'), ('2', 'Software configuration'), ('3', 'Software installation'), ('4', 'Computer consulting'), ('5', 'Audio'), ('6', 'Events in general')], default='1', max_length=1),
        ),
    ]
