# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordermanager', '0012_auto_20180607_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('1', 'Principal'), ('2', 'Administration and finance'), ('3', 'Linking'), ('4', 'Planning and evaluation'), ('5', 'Academician')], default='1', max_length=1)),
                ('building', models.CharField(choices=[('1', 'Teaching 1'), ('2', 'Teaching 2'), ('3', 'Heavy Laboratory'), ('4', 'Library'), ('5', 'Other')], default='1', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
