# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0013_auto_20180607_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('1', 'Pennding'), ('4', 'Done')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('1', 'Principal'), ('2', 'Administration and finance'), ('3', 'Linking'), ('4', 'Planning and evaluation'), ('5', 'Academician')], default='5', max_length=1),
        ),
    ]
