# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0014_auto_20180610_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='questionFive',
            field=models.CharField(choices=[('1', 'What is your level of satisfaction?')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('1', 'Pennding'), ('2', 'Done')], default='1', max_length=1),
        ),
    ]
