# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 04:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordermanager', '0015_auto_20180620_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_equipment_set', to='ordermanager.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Preventive_Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('1', 'Preventive Maintenance'), ('2', 'Corrective Maintenance')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('1', 'Pennding'), ('2', 'on process'), ('3', 'Canceled'), ('4', 'Done'), ('5', 'Pause')], default='1', max_length=1)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('observations', models.CharField(max_length=200, null=True)),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('date_onprocess', models.DateTimeField(blank=True, null=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('date_cancel', models.DateTimeField(blank=True, null=True)),
                ('date_pause', models.DateTimeField(blank=True, null=True)),
                ('technical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Maintenance_technical_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Maintenance_user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='date_pause',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('1', 'Pennding'), ('2', 'on process'), ('3', 'Canceled'), ('4', 'Done'), ('5', 'Pause')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='equipment_maintenance',
            name='preventive_maintenance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preventive_maintenance_set', to='ordermanager.Preventive_Maintenance'),
        ),
    ]
