# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0016_auto_20181007_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
