# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0017_poll_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('1', 'Maintenance of computer equipment'), ('2', 'Configuration in general'), ('3', 'Software installation'), ('4', 'Computer consulting'), ('5', 'Audio and Events'), ('6', 'Problems in general'), ('7', 'Problems in Laboratories')], default='1', max_length=1),
        ),
    ]
